### ISSUE TITLE
Game Doesnt Download

### ISSUE THREAD

**Issue by mehmet-n** [isacucho/FnMacAssistant#11]
Downloaded the IPA, signed it with esign replaced the mobilprovisionfile with my own patched it with FnMacAssistant the game opens but its stuck at 75% downloading and it doesnt show many many GBs it has downloaded

**Comment by isacucho** [comment]
You can see how much it has downloaded by going to finder and searching for a folder called FortniteGame, find the heaviest one and checking the size. It should finish at around 13-15GB. If it doesn't move you can close and reopen the app, the progress won't go away.

**Comment by mehmet-n** [comment]
ok it worked but now I have a new problem I cant press the buttons with my touchpad, or mouse, the game just traps my mouse and I can only exit the game by doing command alt how can I fix this? I have a contrller but I dont think it will work before I get to the lobby, I am currently at the point where it asks me to log in with epic for the first time

**Comment by mehmet-n** [comment]
Got a fix for this: go to the settings from the top left, the to settings and from there turn on Game Control and Touch Alternatives.
