### ISSUE TITLE
Application Size

### ISSUE THREAD

**Issue by pheological** [isacucho/FnMacAssistant#3]
How large is the fortnite application?

**Comment by isacucho** [comment]
The app itself is around 500mb when installed. The game files that are downloaded once you open the game rounds it up at around 15gb. If you download HD textures it will go up to around 30gb. You can find out how much storage the game files are taking by going to finder and searching for a folder called FortniteGame. If you find many of these look for the heaviest, and that’s how much storage it is taking. (The other folders can be inside that first folder)

**Comment by pheological** [comment]
ight tysm
