### ISSUE TITLE
Stuck on "Receive notifications" banner

### ISSUE THREAD

**Issue by Antonio05200** [isacucho/FnMacAssistant#8]
Hello, I followed the instructions and Fortnite works well. I even played. But when I reopened I got this banner and I can't click neither of the two options even if I use the joystick. How can I solve?

<img width="1512" alt="Receive notification " src="https://github.com/user-attachments/assets/5bec13b6-bdee-48b9-908e-dba526afcf72">

**Comment by isacucho** [comment]
When I got this issue, I was able to solve it by closing and reopening the game, or by waiting for the game to go to the lobby. When you get to the lobby this popup should disappear. I honestly don’t know what made it appear in the first place since it’s not the first time you open the game.

**Comment by Antonio05200** [comment]
> When I got this issue, I was able to solve it by closing and reopening the game, or by waiting for the game to go to the lobby. When you get to the lobby this popup should disappear. I honestly don’t know what made it appear in the first place since it’s not the first time you open the game.

I tried reopening the game, but this pop up appears always before I go to the lobby

**Comment by Antonio05200** [comment]
I solved deleting the game and sideloading again. When Fortnite asked notifications permissions from Mac's notifications center I denied them.
